### ISSUE TITLE
Use curent host and port to connect socket

### ISSUE THREAD

**Issue by axel-kummer** [alexgunkel/logbook#2]
Hi Alex, 

the frontend should use the current host and port to connect to socket. Otherwise it will work only for localhost:8080.

**Comment by alexgunkel** [comment]
Hey Axel,

I would prefer to make those thinks configurable. My idea is to use environmental variables, because this would make things easier in a Docker images… I'll try to implement this later today…

**Comment by axel-kummer** [comment]
Hi Alex, 

yes that will fit my needs.

**Comment by alexgunkel** [comment]
Hey @axel-kummer 

I implemented this feature and hope it works for you ;)

**Comment by axel-kummer** [comment]
@alexgunkel Yes, works great so far.
